version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: deviceatlas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend  # Ensure it points to the backend folder
      dockerfile: Dockerfile
    ports:
      - "5012:5012"
    depends_on:
      db:
        condition: service_healthy  # Ensures db is ready before backend starts
    environment:
      DB_HOST: db
      DB_NAME: deviceatlas
      DB_USER: user
      DB_PASSWORD: password
      DB_DIALECT: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "user", "--password=password"]
      interval: 10s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: ./frontend  # Ensure it points to the frontend folder
      dockerfile: Dockerfile
    ports:
      - "5013:80"
    depends_on:
      - backend

volumes:
  mysql_data:
