version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: deviceatlas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  server:
    build: ./backend
    environment:
      DB_HOST: db
      DB_NAME: deviceatlas
      DB_USER: root
      DB_PASSWORD: password
      DB_DIALECT: mysql
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: