services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: device_atlas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --pid-file=/var/lib/mysql/mysql.pid
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "/usr/local/bin/wait-for-it db:3306 -t 30 -- npm start"
    ports:
      - "5012:5012"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: device_atlas
      DB_USER: user
      DB_PASS: password
      DB_DIALECT: mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5013:80"
    depends_on:
      - backend

volumes:
  mysql_data: